# Generated by Django 5.2 on 2025-04-23 14:23

import django.core.validators
import django.db.models.deletion
import simple_history.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Anemometer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Anemometer', max_length=255, unique=True)),
                ('long', models.DecimalField(decimal_places=6, help_text='The longitude coordinates', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))])),
                ('lat', models.DecimalField(decimal_places=6, help_text='The latitude coordinates', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))])),
            ],
        ),
        migrations.CreateModel(
            name='AnemometerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the category', max_length=255, unique=True)),
                ('anemometers', models.ManyToManyField(related_name='categories', to='wind_api.anemometer')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalAnemometer',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(db_index=True, help_text='The name of the Anemometer', max_length=255)),
                ('long', models.DecimalField(decimal_places=6, help_text='The longitude coordinates', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))])),
                ('lat', models.DecimalField(decimal_places=6, help_text='The latitude coordinates', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))])),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical anemometer',
                'verbose_name_plural': 'historical anemometers',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WindReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('200.00'))])),
                ('wind_unit', models.CharField(choices=[('Knots', 'Knots')], default='Knots', max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField(auto_now_add=True)),
                ('anemometer', models.ForeignKey(help_text='The given Anemometer', on_delete=django.db.models.deletion.CASCADE, related_name='wind_readings', to='wind_api.anemometer')),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Tag', max_length=255, unique=True)),
                ('wind_readings', models.ManyToManyField(related_name='tags', to='wind_api.windreading')),
            ],
        ),
    ]
