# Generated by Django 5.2 on 2025-04-11 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wind_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Anemometers',
            new_name='Anemometer',
        ),
    ]
