# Generated by Django 5.2 on 2025-04-11 21:53

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_api', '0002_rename_anemometers_anemometer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemometer',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='anemometer',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='anemometer',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
