# Generated by Django 5.2 on 2025-04-11 22:27

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_api', '0003_alter_anemometer_lat_alter_anemometer_long_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anemometer',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
