# Generated by Django 5.2 on 2025-04-12 10:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_api', '0004_alter_anemometer_wind_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='anemometer',
            name='wind_direction',
            field=models.CharField(choices=[('East', 'East'), ('West', 'West'), ('North', 'North'), ('South', 'South')], default=2, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='anemometer',
            name='wind_gust',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='anemometer',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-90.0')), django.core.validators.MaxValueValidator(Decimal('90.0'))]),
        ),
        migrations.AlterField(
            model_name='anemometer',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('-180.0')), django.core.validators.MaxValueValidator(Decimal('180.0'))]),
        ),
    ]
