# Generated by Django 5.2 on 2025-04-12 10:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_api', '0005_anemometer_wind_direction_anemometer_wind_gust_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anemometer',
            name='date',
        ),
        migrations.RemoveField(
            model_name='anemometer',
            name='time',
        ),
        migrations.RemoveField(
            model_name='anemometer',
            name='wind_direction',
        ),
        migrations.RemoveField(
            model_name='anemometer',
            name='wind_gust',
        ),
        migrations.RemoveField(
            model_name='anemometer',
            name='wind_speed',
        ),
        migrations.CreateModel(
            name='WindReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wind_speed', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('wind_unit', models.CharField(choices=[('Knots', 'Knots')], max_length=15)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('anemometer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wind_api.anemometer')),
            ],
        ),
    ]
