# Generated by Django 5.2 on 2025-04-20 22:06

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_api', '0007_alter_anemometer_lat_alter_anemometer_long_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='windreading',
            name='anemometer',
        ),
        migrations.AddField(
            model_name='anemometer',
            name='wind_readings',
            field=models.ManyToManyField(blank=True, help_text='For submitting wind speed readings', null=True, to='wind_api.windreading'),
        ),
        migrations.AlterField(
            model_name='windreading',
            name='wind_speed',
            field=models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('200.00'))]),
        ),
    ]
