# Generated by Django 5.2 on 2025-04-21 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_api', '0008_remove_windreading_anemometer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anemometer',
            name='wind_readings',
        ),
        migrations.AddField(
            model_name='windreading',
            name='anemometer',
            field=models.ForeignKey(default=2, help_text='The given Anemometer', on_delete=django.db.models.deletion.CASCADE, to='wind_api.anemometer'),
            preserve_default=False,
        ),
    ]
