# Generated by Django 5.2 on 2025-04-22 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_api', '0009_remove_anemometer_wind_readings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='windreading',
            name='anemometer',
            field=models.ForeignKey(help_text='The given Anemometer', on_delete=django.db.models.deletion.CASCADE, related_name='wind_readings', to='wind_api.anemometer'),
        ),
        migrations.AlterField(
            model_name='windreading',
            name='date',
            field=models.DateField(),
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the Tag', max_length=255, unique=True)),
                ('anemometer', models.ManyToManyField(help_text='The given Anemometer', related_name='tags', to='wind_api.anemometer')),
            ],
        ),
    ]
