# Generated by Django 5.2 on 2025-04-22 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wind_api', '0011_remove_tags_anemometer_tags_wind_readings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='wind_readings',
            field=models.ManyToManyField(related_name='tags', to='wind_api.windreading'),
        ),
    ]
